# GatewayProxy - APISIX-specific CRD that bridges Gateway API with APISIX
# This configures how HTTPRoutes are synced to the APISIX gateway
# In APISIX Ingress Controller 2.0.0, GatewayProxy must be referenced via IngressClass
apiVersion: apisix.apache.org/v1alpha1
kind: GatewayProxy
metadata:
  name: apisix-gateway-proxy
  namespace: apisix-argocd
spec:
  # Provider configuration for APISIX Control Plane
  provider:
    type: ControlPlane
    controlPlane:
      endpoints:
        - http://apisix-admin.apisix.svc.cluster.local:9180
      auth:
        type: AdminKey
        adminKey:
          valueFrom:
            secretKeyRef:
              name: apisix-admin-credentials
              key: admin-key