# GatewayProxy - APISIX-specific CRD that bridges Gateway API with APISIX
# This configures how HTTPRoutes are synced to the APISIX gateway
# Note: GatewayProxy should be in the apisix namespace for the controller to discover it
apiVersion: apisix.apache.org/v1alpha1
kind: GatewayProxy
metadata:
  name: apisix-gateway-api-proxy
  namespace: apisix
spec:
  # Provider configuration for APISIX Control Plane
  provider:
    type: ControlPlane
    controlPlane:
      endpoints:
        - http://apisix-admin.apisix.svc.cluster.local:9180
      auth:
        type: AdminKey
        adminKey:
          valueFrom:
            secretKeyRef:
              name: apisix-admin-credentials
              key: admin-key