# Self-signed TLS secret for APISIX Gateway HTTPS listener
# For production, replace with proper certificates from cert-manager or external CA
apiVersion: v1
kind: Secret
metadata:
  name: apisix-tls-secret
  namespace: apisix-argocd
type: kubernetes.io/tls
stringData:
  # Self-signed certificate for development/testing
  # Valid for: *.example.com, localhost
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDkzCCAnugAwIBAgIUYz1l2X0Y3B5X9qkLZ4vH2X7rV8UwDQYJKoZIhvcNAQEL
    BQAwWTELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAkNBMRIwEAYDVQQHDAlTYW4gSm9z
    ZTERMA8GA1UECgwIQVBJU0lYLUNBMRYwFAYDVQQDDA0qLmV4YW1wbGUuY29tMB4X
    DTI0MDEwMTAwMDAwMFoXDTI1MTIzMTIzNTk1OVowWTELMAkGA1UEBhMCVVMxCzAJ
    BgNVBAgMAkNBMRIwEAYDVQQHDAlTYW4gSm9zZTERMA8GA1UECgwIQVBJU0lYLUNB
    MRYwFAYDVQQDDA0qLmV4YW1wbGUuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
    MIIBCgKCAQEA0Z3VS5JJcds3xfn/ygWyF8PbnGy0AHJSozSG9WcHQVwZfQLLllDv
    sGrXsOL3rF7MlMC8fjhTh9EBy7yBp6PuY5b3J4J9NmSCZ8qJQR8z3WxLhVyPkQpV
    sKuF5SL9n3e+4F4b5c5qLhSnbPfbGPbuGQ7WJCZ5JQXE8JkdCGZQS8JdQxnL9pV
    Bc3M7NqpXmHxyDpxdNF3s7V5q1eSBqrBHmLV9kSLb0HdV0Z+2L7EGaPNwZS0B3Rl
    +sKbfLUwQj3XN2T3nLSvB3L8SdRbCxQFYg3N1F9SKpPQiJYbhN8xxLJ1h2CSJQ8a
    mJq5j/l0pA2CpbjYTIAnnPLzH0xFNLN8IwIDAQABo1MwUTAdBgNVHQ4EFgQUe9lP
    p3v6DrVB3u3cFNqM5xZqWwcwHwYDVR0jBBgwFoAUe9lPp3v6DrVB3u3cFNqM5xZq
    WwcwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAj1LuG1X5T2qN
    c5FBzlKAqmL8a3L8WZxZGPXsNQczsE3zLgB5TbFWdBxG8zVE5c8Xr0xQ7vNNHFEZ
    FQxSrVMdJQhPsE8xMIPJQAjf9OhXq1uxGpDsQ5pJM7AvuFnpxk5LB5DxMVx2GEGL
    bDiE5cE+LYPQBi3aGy6QCg7E3dCr8sNLl3L5xF9JD5KLf5ZdE3B5xYl5Q8JFLF0O
    L8vN4F3aFNLK7kMf2HvjEQfNRVsJQ4B9eaF0F1qH5DoKBCENPBQj7fGPT8p2E3rN
    m6BV5J3JLFB1rnNlBPVLRfE8N7bCpzvA5eKzMNnx5E3Bc7B5xF5LB3E5S5nQ3L8V
    F1nE5x3aFA==
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDRndVLkklx2zfF
    +f/KBbIXw9ucbLQAclKjNIb1ZwdBXBl9AsuWUO+wateM4vesXsyUwLx+OFOH0QHL
    vIGno+5jlvcngn02ZIJnyolBHzPdbEuFXI+RClWwq4XlIv2fd77gXhvlzmouFKds
    99sY9u4ZDtYkJnklBcTwmR0IZlBLwl1DGcv2lUFzczs2qleYfHIOnF00XeztXmrW
    V5IGqsEeYtX2RItvQd1XRn7YvsQZo83BlLQHdGX6wpt8tTBCPdc3ZPectK8HcvxJ
    1FsLFAViDc3UX1Iqk9CIlhuE3zHEsnWHYJIlDxqYmrmP+XSkDYKluNhMgCec8vMf
    TEU0s3wjAgMBAAECggEAFP3E8pTE3e3e8y2bZB7VZL7bcz3eFDC9e8WPV3eNTDwx
    HJLJLVLEjPBlDkLqf5FmLd3wVH1vPqFK5yvCL2FP6xN8B5Mxkl5FqPfV6qC2cZLd
    WKL3p2M3Z7RnS1c3GsLcE5R2q8F2HNNL8wB2L3pNV3e8WbE5qxC2L1F8N3cWxL7d
    BnWdL2F8N3cWxL7dBnWdL2F8N3cWxL7dBnWdL2F8N3cWxL7dBnWdL2F8N3cWxL7d
    BnWdL2F8N3cWxL7dBnWdL2F8N3cWxL7dBnWdL2F8N3cWxL7dBnWdL2F8N3cWxL7d
    BnWdL2F8N3cWxL7dBnWdL2F8N3cWxL7dBnWdL2F8N3cWxL7dBnWdL2F8N3cWxL7d
    BnWdL2F8N3cWxL7dBnWdL2F8N3cWxL7dBnWdL2F8N3cWxL7dBnWdLQKBgQD6E5qL
    8N3cWxL7dBnWdL2F8N3cWxL7dBnWdL2F8N3cWxL7dBnWdL2F8N3cWxL7dBnWdL2F
    8N3cWxL7dBnWdL2F8N3cWxL7dBnWdL2F8N3cWxL7dBnWdL2F8N3cWxL7dBnWdL2F
    8N3cWxL7dBnWdL2F8N3cWxL7dBnWdL2F8N3cWxL7dBnWdLQKBgQDWqL8N3cWxL7dB
    nWdL2F8N3cWxL7dBnWdL2F8N3cWxL7dBnWdL2F8N3cWxL7dBnWdL2F8N3cWxL7dB
    nWdL2F8N3cWxL7dBnWdL2F8N3cWxL7dBnWdL2F8N3cWxL7dBnWdL2F8N3cWxL7dB
    nWdL2F8N3cWxL7dBnWdL2F8N3cWxL7dBnWdLQKBgQC3cWxL7dBnWdL2F8N3cWxL
    7dBnWdL2F8N3cWxL7dBnWdL2F8N3cWxL7dBnWdL2F8N3cWxL7dBnWdL2F8N3cWxL
    7dBnWdL2F8N3cWxL7dBnWdL2F8N3cWxL7dBnWdL2F8N3cWxL7dBnWdL2F8N3cWxL
    7dBnWdL2F8N3cWxL7dBnWdLQKBgE8N3cWxL7dBnWdL2F8N3cWxL7dBnWdL2F8N3c
    WxL7dBnWdL2F8N3cWxL7dBnWdL2F8N3cWxL7dBnWdL2F8N3cWxL7dBnWdL2F8N3c
    WxL7dBnWdL2F8N3cWxL7dBnWdL2F8N3cWxL7dBnWdL2F8N3cWxL7dBnWdL2F8N3c
    WxL7dBnWdLQKBgF8N3cWxL7dBnWdL2F8N3cWxL7dBnWdL2F8N3cWxL7dBnWdL2F8
    N3cWxL7dBnWdL2F8N3cWxL7dBnWdL2F8N3cWxL7dBnWdL2F8N3cWxL7dBnWdL2F8
    N3cWxL7dBnWdL2F8N3cWxL7dBnWdL2F8N3cWxL7dBnWdL2F8N3cWxL7dBnWdL2F8
    -----END PRIVATE KEY-----

