apiVersion: v1
kind: Secret
metadata:
  name: apisix-tls-secret
  namespace: apisix-argocd
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIC/DCCAeSgAwIBAgIJAKHLPpEeY3IxMA0GCSqGSIb3DQEBCwUAMCkxFjAUBgNV
    BAMMDSouZXhhbXBsZS5jb20xDzANBgNVBAoMBkFQSVNJWDAeFw0yNTEyMTEwOTEz
    MzJaFw0yNjEyMTEwOTEzMzJaMCkxFjAUBgNVBAMMDSouZXhhbXBsZS5jb20xDzAN
    BgNVBAoMBkFQSVNJWDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANXd
    AZoa2ko7Jv01piXfDKtmAdgIHjLFLA/9vKOEWrysC2xRNqLyZ+vsZzo4Cl3IPpoL
    Qx7+APBrYiRaM+uxx7cFaKfQ5/Ot0c09GJ8oTbKTr6iylTaRXcfgLOcrWXqfVZMV
    RG37NcInjj7HW8p/XHTCz8C7+v1qywmy3qIvbHGJy+macW3c7C7uuTkQ1ybWD7t5
    IEL2Vw/sj2it45uVnQBngmo79xjzP3PNC8jaFJyWXLu3xYeIiMcnjSyThj5iCOJb
    8i5afkUOvZHAG46IqKhoUxmoeDV1NsXZgjqfiKWsAdjBJe2B89LqSMO5zX0xSyHo
    fpaSCaQ0TljP11qKPCu5AgMBAAGjJzAlMCMGA1UdEQQcMBoHDSouZXhhbXBsZS5j
    b22CCWxvY2FsaG9zdDANBgkqhkiG9w0BAQsFAAOCAQEAUeaVBSxWDnbTQraS0GYz
    ZJ5Cn9GOOHYz/cY2+5jfzje35g7lM5gx3ttbaLE5eqR/p9GpgPRxvi5JPH7IcfKb
    /RkeeHPdWzR+kJi3CaTyzntgn80wGCJ5dS6plyW+FcQq+qyk4mTIgB6ZU+K9Y1su
    ftDZBqcaOqE0iQKd7tOax/F0y9DLyFBvS3qTuMVznhHOocS5PV1jMKXmUyxy2Vhs
    mQ54sjE+/4BJI8LBrN38+1kgYIYyzbYXfaediEOu+ol7vUtk8P0jqsGezq8n6lNE
    zZ5hNplOG0BWjobPs0uskI6rbur9bXXdYufmpBoVuZGOdUPvnq0pZ0TAYjsG6v+3
    nw==
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDV3QGaGtpKOyb9
    NaYl3wyrZgHYCB4yxSwP/byjhFq8rAtsUTai8mfr7Gc6OApdyD6aC0Me/gDwa2Ik
    WjPrsce3BWin0OfzrdHNPRifKE2yk6+ospU2kV3H4CznK1l6n1WTFURt+zXCJ44+
    x1vKf1x0ws/Au/r9assJst6iL2xxicvpmnFt3Owu7rk5ENcm1g+7eSBC9lcP7I9o
    reOblZ0AZ4JqO/cY8z9zzQvI2hSclly7t8WHiIjHJ40sk4Y+YgjiW/IuWn5FDr2R
    wBuOiKioUxmoeDV1NsXZgjqfiKWsAdjBJe2B89LqSMO5zX0xSyHofpaSCaQ0TljP
    11qKPCu5AgMBAAECggEBAIEPtK3JUr7FX8wjGjd0mfK9xpMWoxLEhsjHuZV8hD2k
    HeiqQiyn2Ss5KTqrIyZhd9YCwejsJKjyRPHnNbohOYMr0nKj0bbuyNPw8PDro6gH
    FFTcIMwjgdLjaHXBZWhoy33NsdQla9XVhTRBnxVfMu6LulB3oQpZ7lnWBiEeOXVy
    NhsgAhvZCmA7Maxz54eburQhpOpO2cxL7UvF1sVxA/ZiZs+lun7b2W5AGtbtiU4k
    ijcgrBzz1SjWUdE5dejt2i1mE4EzZ25fTvWeu6dguRZTUN6EVZKSkbHNstfW5cvu
    RVyHEwDHr6mffv4w9b/ZROGIAPkyZA8aZ/c5weJWpgECgYEA+Kle+fX+Yxr7skSQ
    M1M7pA5hUrrFnRa7fxkTo+frrMTmaoa2TTchzqyfTb9i2QQvPtrbux1DGR+R1WJV
    ChD+vJDOmQGH1xkNviEcNk5zDn70xn2d8jfcgOwMlnGaSXDFaaP5s1mqWao6FFhV
    YNxYZ9EswVGB7j98cg+3hgp49uECgYEA3Cy8RI3RUQcsvUvz+QZkzDnCDp97Jnaf
    rIPUseMSdyE/h2OkQNMO0F40nAJX3S9S9UHRDgQ1Ss6X6hmHIO8VAjj6zEDoms9s
    wvpU/x1wfZIiiMAe9u6kaD2pZNBCFQMXJGmWijAxPI12++4ppcU7ZiV5+WN2KUrT
    5qmJNp0Kx9kCgYBZ1e7/RXVDXtNCI20pbc+lRKC6n8mXKEhS8b9bvwUxJO3N3J9u
    JBXtsgXXs+ZFWzKqda1e24KLSBGK0vzAJ0Ww4GwTcS8fcei6IQItSIhe21UZhPaU
    NMRQO3eMvrwr/jcEJH6o4iMeQ9a51PP7i3/Q+gw+R3E2nu8Z0j3OimgLYQKBgQCH
    3Q8cGos0vgGsmgbl/z0KDQYjsePzezXS5dLFJoMJgjnKmQENg2/bwpYiQwvnEEHX
    2BJh3NTp4Yw6yB/rgbzsDy8sBU3D4gWSV5lFh+wXgKrQygURiXdoX8x8ykpM3whT
    ztg3U7++RulKUs/eXFPoF24qJ2cN2f/ikXF7gvLZGQKBgEu86JP6Z0LU8So1jzUC
    lKhmin9DULVr2LHop3jsWZF9CkkLaAzCmJQgtEJyeWjzUMTFcwFoaV3fB6JDYecR
    /U2iQlFowURDALh/GbLFSAFbTZBU7jAmrPNVQGlChqa7yB/YgonVz9xm+UvjAWZh
    rtjn2a1xGQlWcM/Zq6p/4sip
    -----END PRIVATE KEY-----
